on:
  push:
    branches:
      - master
    tags:
      - 'v*'

name: publish_docker_image

jobs:
   publish_docker_image:
    runs-on: ubuntu-latest
    env:
      IMAGE: italia/spid-saml-check

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Docker image tags
        run: |
          TAGS=${IMAGE}:$(echo ${GITHUB_REF##*/})
          TAGS="$TAGS,${IMAGE}:${GITHUB_SHA::8}"

          echo "TAGS=${TAGS}" >> $GITHUB_ENV

      - name: Add latest tag to Docker image on release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAGS=$(echo "${{ env.TAGS }}")
          TAGS="$TAGS,${IMAGE}:latest"

          echo "TAGS=${TAGS}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.TAGS }}
